### ISSUE TITLE
Required constraint not working with upload element

### ISSUE THREAD

**Issue by Talroon** [ameos/ameos_form#1]
The "required" constraint does not seem to work with the "upload" element.

If`$value` is null (if no file is uploaded), no constraint gets validated.
https://github.com/ameos/ameos_form/blob/master/Classes/Elements/Upload.php#L172-L175

If a file is uploaded, the `$value` passed from determineErrors is an array but does not contain "upload". Because of that `trim($value)` is called resulting in the warning `trim() expects parameter 1 to be string, array given`
I guess this bug could be solved by checking if `$value` is an array that has a (non-empty) "name".
https://github.com/ameos/ameos_form/blob/master/Classes/Constraints/Required.php#L28-L33

**Comment by ameos** [comment]
Hi Talroon,

Sorry for the late answer.
The bug is fixed. Thanks for your reporting.

Stéphane
